# Generated by Django 3.2.5 on 2021-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_unlimited',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
